export default {
  COIN_BUY: 'coin/BuyCoin',
  COIN_CREATE: 'coin/CreateCoin',
  COIN_SELL: 'coin/SellCoin',
  COIN_SEND: 'coin/SendCoin',
  COIN_MULTISEND: 'coin/MultiSendCoin',
  COIN_SELL_ALL: 'coin/SellAllCoin',
  COIN_REDEEM_CHECK: 'coin/RedeemCheck',
  VALIDATOR_CANDIDATE: 'validator/declare_candidate',
  VALIDATOR_DELEGATE: 'validator/delegate',
  VALIDATOR_SET_ONLINE: 'validator/set-online',
  VALIDATOR_SET_OFFLINE: 'validator/set-offline',
  VALIDATOR_UNBOND: 'validator/unbond',
  VALIDATOR_CANDIDATE_EDIT: 'validator/edit-candidate',
  MULTISIG_CREATE_WALLET: 'multisig/CreateWallet',
  MULTISIG_CREATE_TX: 'multisig/CreateTransaction',
  MULTISIG_SIGN_TX: 'multisig/SignTransaction',
};
